### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by danielytics** [oakes/Nightlight#19] opened 2017-02-25 10:46 UTC
Currently nightlights REPL and instarepl don't work in safari (and therefore won't work on iOS).

The REPL doesn't correctly add newlines after evaluating an expression. The instarepl doesn't update (you can toggle it off and back on to get the evaluation, but its not exactly "instant" then)

**Comment by oakes** [comment] 2017-02-27 17:06
Hmm it looks like it only is broken in mobile safari. It looks like the REPL works fine in desktop safari. Still trying to investigate the cause.

**Comment by danielytics** [comment] 2017-02-27 17:09
@oakes Thank you so much for looking into this! Let me know if there's anything I can do to help.

**Comment by oakes** [comment] 2017-02-27 20:24
Fixed! I pushed the fix to Nightcoders.net as well so please try it again on your iPad and let me know if anything is still not working.

**Closed as completed by oakes** 2017-02-27 20:24 UTC

**Comment by danielytics** [comment] 2017-02-28 00:04
I can confirm that it works on iPad! Thanks very much. 💃
